install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_baseu_net-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_baseu_xml-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_adv-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_core-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_adv-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_aui-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_adv-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_adv-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_aui-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_core-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_aui-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_gl-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_core-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_gl-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_html-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_core-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_html-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_html-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_html-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_xrc-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_adv-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_adv-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_xrc-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_core-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_xrc-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu_xml-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu_xml-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_xrc-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_xrc-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_core-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_qa-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_qa-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu_xml-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu_xml-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_qa-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_osx_cocoau_core-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_osx_cocoau_core-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_webview-3.1.1.0.0.dylib
install_name_tool -change /usr/local/lib/libwx_baseu-3.1.1.0.0.dylib @executable_path/../Frameworks/libwx_baseu-3.1.1.0.0.dylib Frameworks/libwx_osx_cocoau_webview-3.1.1.0.0.dylib
echo "Fertig"