//
// File Autogenerated by SaltyPaw's PNG conversion script
//
//
#ifndef _IMAGES_BIN2C_H_
#define _IMAGES_BIN2C_H_
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
# include <wx/wx.h>
#endif
#include <wx/mstream.h>
//
extern void initialize_bitmaps(void);
//
extern wxBitmap *_img_JavaScript_pi_panel_icon;
//
#endif // _IMAGES_BIN2C_H_
