/* Autogenerated by png2wx.pl on Thu Oct 29 12:01:00 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_sweepplot;

#ifdef SWEEPPLOT_USE_SVG
extern wxString _svg_sweepplot;
extern wxString _svg_sweepplot_rollover;
extern wxString _svg_sweepplot_toggled;
#endif

#endif /* ICONS_H */
