/* Autogenerated by png2wx.pl on Sat Jun 29 18:48:03 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_trimplot;

#endif /* ICONS_H */
