/* Autogenerated by png2wx.pl on Sun Feb  8 11:49:02 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_trimplot;

#endif /* ICONS_H */
