/* Autogenerated by png2wx.pl on Sun Jul 17 16:36:39 2016 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_Bullet_green;
extern wxBitmap *_img_Bullet_red;
extern wxBitmap *_img_Bullet_yellow;
extern wxBitmap *_img_logbook_pi;

#endif /* ICONS_H */
