/* Autogenerated by png2wx.pl on Sun Oct 30 17:26:20 2011 */
#ifndef ICONS_H
#define ICONSS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);
extern void deinitialize_images(void);

extern wxBitmap *_img_iacfleet_pi;

#endif /* ICONS_H */
