/* Autogenerated by png2wx.pl on Mon May 26 18:51:45 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_marina_grn;
extern wxBitmap *_img_anchor_blu;
extern wxBitmap *_img_club_pur ;
extern wxBitmap *_img_fuelpump_red;
extern wxBitmap *_img_pier_yel;
extern wxBitmap *_img_ramp_azu;



#endif /* ICONS_H */
