/* Autogenerated by png2wx.pl on Fri Dec 27 15:58:13 2019 */
#ifndef ICONTEST_H
#define ICONTEST_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_calculator_panel_icon;

#endif /* ICONTEST_H */
