/* Autogenerated by png2wx.pl on Sun Apr  1 04:36:01 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_kmloverlay_pi;
extern wxBitmap *_img_kmloverlay;
extern wxBitmap *_img_minus;
extern wxBitmap *_img_plus;
extern wxBitmap *_img_point;
extern wxBitmap *_img_undersized;

#endif /* ICONS_H */
