/* Autogenerated by png2wx.pl on Sun Mar 15 14:50:05 2020 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_active;
extern wxBitmap *_img_activewpt;
extern wxBitmap *_img_inactive;
extern wxBitmap *_img_setting;
extern wxBitmap *_img_target;
extern wxBitmap *_img_targetwpt;
extern wxBitmap *_img_toggled;

#endif /* ICONS_H */
