/* Autogenerated by png2wx.pl on Sun Mar 15 14:50:05 2020 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_active;
extern wxBitmap *_img_target;
extern wxBitmap *_img_toggled;

#ifdef navdata_USE_SVG
extern wxString _svg_navdata;
extern wxString _svg_navdata_rollover;
extern wxString _svg_navdata_toggled;
#endif

#endif /* ICONS_H */
