/* Autogenerated by png2wx.pl on Fri Jul 15 12:32:43 2016 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_messagescope;

#endif /* ICONS_H */
