/* Autogenerated by png2wx.pl on Wed Jul 25 21:55:14 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_calc;

#endif /* ICONS_H */
