/* Autogenerated by png2wx.pl on Wed Jul 25 21:55:14 2012 */
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif
#include <wx/mstream.h>
#include "icons.h"
#include <wx/filename.h>

wxBitmap *_img_calc;

#ifdef CALCULATOR_USE_SVG
#include "ocpn_plugin.h"
wxString _svg_calculator;
wxString _svg_calculator_toggled;
#endif

void initialize_images(void)
{
	{
		wxMemoryInputStream sm("\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\000 \000\000\000 \b\006\000\000\000szz\364\000\000\000\004sBIT\b\b\b\b|\bd\210\000\000\000\011pHYs\000\000\023\257\000\000\023\257\001c\346\216\303\000\000\000\031tEXtSoftware\000www.inkscape.org\233\356<\032\000\000\001\262IDATX\205\355\226\277J\035A\024\306\277o\274\346\212\267\220+\004\004\033\23303\020\256)\242\235\344\001,\014v\022I\247\017`!v\022\322\330\205\024!$\257\221>\257qg,|\003I\241$f\227\345\263\211\260\254\263k\356\232\353\037rO\371\235\3039?v\316\2673\300\377\036\254\n\336\373}I\213c\232\367)\204p\\\026:\325\nIo\000\014\3061\235\3447\000\315\000\377\"$\025$\177\225\244.\200\351Tm-\200\244\327\000\236\264\0010\306\314I2\245^\333$\327F\002\000\360=\306x\326\006\240\032\316\271\227\000\222\000&%\336e\324~\001\222\037\235s9\200\\\322y\233\346$\177\223\374\011`Y\322h\000\000\226\000\024\000\346H\226\317\263O\362G\242\336\000\350\0038-i\375?\203\237\326\riZ\302\215\324\016Xk\217B\b\aU}0\030\364\362<\337\033\016\207\357\2539\347\334W\000;\2519\367\276\003\023\200\011@\323\177\340\235\2656#y!i\246\244\277\262\326\036U\353\263,\233&\271b\255\355\001\2001&\227d$MIZ%\257]\274\315\000\222\016\353l\030c\254\265a\2141e\303y\000\313\2519\367~\004\023\200\207\013\320\351tzw\001P\353\202\242(v\235s3\345\227\rp\263\r\235s\263\0002I\335\253\\[\033~hc\303\020\302\304\206\217\013\240\351.\330\362\336_TuI\317\275\367o\253z\226e]\222/R9I\317F\006\000\360\245\356!)i\275F\a\200\315\206\2367\003H\372Lra\224&\177\033EQ\234\214\243\357\255\342\022\235;\266\201c\r\006\347\000\000\000\000IEND\256B`\202", 565);
		_img_calc = new wxBitmap(wxImage(sm));
	}

#ifdef CALCULATOR_USE_SVG
    wxFileName fn;
    fn.SetPath(*GetpPrivateApplicationDataLocation() + wxFileName::GetPathSeparator());
    fn.AppendDir(_T("plugins"));
    fn.AppendDir(_T("calculator_pi"));
    fn.AppendDir(_T("data"));
    fn.SetFullName(_T("calculator_pi.svg"));
    _svg_calculator = fn.GetFullPath();
    fn.SetFullName(_T("calculator_pi_toggled.svg"));
    _svg_calculator_toggled = fn.GetFullPath();
        
#endif
	return;
}
