#define PLUGIN_VERSION_MAJOR 5
#define PLUGIN_VERSION_MINOR 5
#define PLUGIN_VERSION_PATCH 0
#define PLUGIN_VERSION_DATE "2023-03-07"
#define PLUGIN_VERSION "radar_pi v5.5.0"
#define PLUGIN_VERSION_WITH_DATE "radar_pi v5.5.0 vom 07.03.2023"
#define API_VERSION       "@API_VERSION@"
