#define PLUGIN_VERSION_MAJOR 5
#define PLUGIN_VERSION_MINOR 3
#define PLUGIN_VERSION_PATCH 0
#define PLUGIN_VERSION_DATE "2021-17-17"
#define PLUGIN_VERSION "radar_pi v5.3.0"
#define PLUGIN_VERSION_WITH_DATE "radar_pi v5.3.0 vom 17.12.2021"
#define API_VERSION       "@API_VERSION@"
